os: windows
language: rust
rust:
  - stable

script:
  - cargo build --release
  - cargo test --release

deploy:
  provider: releases
  api_key:
    secure: "hzSydX6EH35QUzZp8N3NASCT8B2/rmYdt3qj8G3Yl35vHIYbs/4ZIdicB/IwuwVfO+H3cbXl549h2eVKOzCv5j0U3VUQPy85NznYYzrPppUBzoM0JF62OVDDsNyWn5s0oQIA2ISnz/OoB2PZnOB+ImRHnbSz898eQ0xfC+JlGlUiYeEccuIxRdUM3Z7SpPzcFLI+tSE1jl41ubGouHrHDw73b0Y1DFotzrZ2GhK+og3jHSjae37++N+t/SQbg38v4bfEdYV6LzzLgd69NgK4Uyk/C31wLqevmG3HyN/4M9Xc7ZJIJ6OFoeMUnlY84ZJV1yxez3hEtBb9VEmqgB/iMyJmGthJ6K22xKDmD4RwTASw+Reo9mAMXKYtHGlMq+/fnABCwJgsTWQs3BfNMeiJ9mogZWCRxljgdx4ZttWMc5tZXppNVcUB/V01KEMIvsVZCQr9rdj8G/4ybnaG6zlfszyledXap2z++b7RLWn1D3/7lxV3bNRgUQTJr/jm36klvrW2wjd/XL16rLp8t73JBTKnWSZlUR8TG5NqRy6qtPauewVzEWSDyTz2Jw/CLqsM1Rx2ob8bV+fK78uluid3L4PHOVlWB7gEpKhJJlOX4wridu1OYWKty5aNiZd18Qbk0H3etTdtu0D+UStqZkHYBUQNQZgDUTtSdkQ/NnaWFOg="
  file: "target/release/foxsee.exe"
  skip_cleanup: true
  on:
    tags: false
