os: windows
language: rust
rust:
  - stable

script:
  - cargo build --release
  - cargo test --release

deploy:
  provider: releases
  api_key:
    secure: kuvcWqX8JLHZ+Akt/w3jIHBU3Mj6dytK3gZI/9KGdzHKdpc2jT+PpX8VglXmSxlJa4cvborZ+Bp02h00serIH8uguv45ggz45wmmA0op5N7HWS4NTa7vtYoV1qLhoNUp6g9yWOOE+LRTDJktSTMKKi7GhhKA4OBLviqbAq9drB5IHmyAWkPtfBZtRRAA8Qf1eNAhcVvUmJazyU1wBCI/IU1HeeaPNywyvguVg12MmzsZ+UQqQrbM7pweMYhj4ESR+I8/eCfsfw4YCfmlWLSjcrttxZ00gPhU6T/UrDaSzmbTOz26RwMQVPsumx1upHIbRciL5cC6npov0Cst+RCo22LifoVeor42rek4HeV7n8M9fIEWob7c9WsvMcGu6qoih5szHzL8T9pwapjuGHg+tLeAeDUtt+8vA9u+XVYwVEvOPF1urmZemRRgRVeBTTfJBYKCYB5ElaNe53cW2QEtfXlkdgEgwkSt9GRcJNtt4OiZRLivE//BEgh8BfjS4bDsVDcjswO76XsUSjFEWq7PoaG95C6soPon3bUxLuI2vLqGJPiFJX14dpB1ymnIcQSMYpT9CEFcPN25OswYMLaGJFkYdxDGjEJjlFY205jpaflOYKI5qbebtHQyoFbRSlNZGRAvI/nMvxWhDbL8Iw4VJ0TF6zYwUQA2SGHcwTMgjuc=
  file: target\release\foxsee.exe
  skip_cleanup: true
  draft: true
  on:
    tags: false
    branch: master
